name: Convert domaintxt to list
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.x

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Get project dependencies & run
        run: |
          go run .
          
#       - name: Generate txt file
#         run: |
#           cd output
#           cp direct.list direct.txt
#           cp cnblock.list cnblock.txt

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          path: output
 
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          echo "::set-output name=status::success"        

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: output/*

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
