name: Convert domaintxt to list
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.x

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Get project dependencies & run
        run: |
          go run main.go
          

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          path: output
 
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
          touch release.txt
          echo "::set-output name=status::success"        

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: output/*

      # - name: Push to release branch
      #   run: |
      #     cd publish
      #     git init
      #     git config --local user.name "${{ github.actor }}"
      #     git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      #     git checkout -b release
      #     git add .
      #     git commit -m "${{ env.RELEASE_NAME }}"
      #     git remote add origin "https://${{ github.actor }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}"
      #     git push -f -u origin release
      #     cp -af lite/Country.mmdb Country-lite.mmdb

      - name: Git push assets to "release" branch
        run: |
          cd output || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ steps.tag.outputs.release_tag }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
